# Save and load Trained Model(pickle and joblib)

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

/home/harish/my_project_dir/my_project_env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = pd.read_csv('homeprices.csv')

In [4]:
df.head(5)

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [14]:
reg = LinearRegression()

In [15]:
model = reg.fit(df[['area']],df.price)

In [19]:
model.coef_

array([135.78767123])

In [20]:
model.intercept_

180616.43835616432

In [18]:
model.predict([[5000]])

array([859554.79452055])

In [21]:
model.score(df[['area']],df.price)

0.9584301138199486

In [23]:
import pickle

In [24]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f )

In [25]:
with open('model_pickle','rb') as f:
    m = pickle.load(f)

In [26]:
m.predict([[6000]])

array([995342.46575342])

In [27]:
from sklearn.externals import joblib

/home/harish/my_project_dir/my_project_env/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [28]:
joblib.dump(model,'joblib_model')

['joblib_model']

In [29]:
L_model = joblib.load('joblib_model')

In [32]:
L_model.predict([[6000]])

array([995342.46575342])